backtick_references = true
description = 'A set of useful containers and utilities for Lua code.'
file = {
    'init.lua',
    'src/Array.lua',
    'src/HashMap.lua',
    'src/MultiSet.lua',
    'src/Set.lua',
    'src/iterx.lua',
    'src/pprint.lua',
    'src/stringx.lua',
}
format = 'discount'
no_space_before_args = true
prettify_files = 'show'
pretty = true
project = 'Rune'
readme = 'README.md'
sort = true
title = project .. ' Documentation'
